version: '3.2'
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: blog_backend
    # guest app port: 3001
    ports:
      - ${BE_PORT:-4001}:3001
    networks:
      - blog_net
    environment:
      - JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
      - JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
      - GRAPHQL_PLAYGROUND=$GRAPHQL_PLAYGROUND
      - TYPEORM_HOST=$DB_HOST
      - TYPEORM_PORT=${DB_PORT:-3306}
      - TYPEORM_USERNAME=${DB_USER:-root}
      - TYPEORM_PASSWORD=${DB_PASSWORD:-$DB_ROOT_PASSWORD}
      - TYPEORM_DATABASE=${DB_NAME:-blog_app}

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - GRAPHQL_URL=$GRAPHQL_URL
        - GRAPHQL_WS=$GRAPHQL_WS
        - REST_URL=$REST_URL
    container_name: blog_frontend
    depends_on:
      - backend
    # guest app port: 3000
    ports:
      - ${FE_PORT:-4000}:3000
    networks:
      - blog_net

networks:
  blog_net:
    driver: bridge
